[PlankDrawingTheme]
#The roundness of the top corners.
TopRoundness=0
#The roundness of the bottom corners.
BottomRoundness=0
#The thickness (in pixels) of lines drawn.
LineWidth=0
#The color (RGBA) of the outer stroke.
OuterStrokeColor=0;;0;;0;;0
#The starting color (RGBA) of the fill gradient.
FillStartColor=40;;40;;40;;0
#The ending color (RGBA) of the fill gradient.
FillEndColor=30;;30;;30;;0
#The color (RGBA) of the inner stroke.
InnerStrokeColor=75;;75;;75;;0
